export const CATCH_POKEMON = 'CATCH_POKEMON'
export const CATCH_POKEMON_START = 'CATCH_POKEMON_START'
export const CATCH_POKEMON_SUCCESS = 'CATCH_POKEMON_SUCCESS'
export const CATCH_POKEMON_ERROR = 'CATCH_POKEMON_ERROR'

export const REMOVE_POKEMON = 'REMOVE_POKEMON'
export const REMOVE_POKEMON_START = 'REMOVE_POKEMON_START'
export const REMOVE_POKEMON_SUCCESS = 'REMOVE_POKEMON_SUCCESS'
export const REMOVE_POKEMON_ERROR = 'REMOVE_POKEMON_ERROR'