export const FETCH_DETAIL = 'FETCH_DETAIL'
export const FETCH_DETAIL_START = 'FETCH_DETAIL_START'
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS'
export const FETCH_DETAIL_ERROR = 'FETCH_DETAIL_ERROR'

